### ISSUE TITLE
Allow passing AWS cli specific cli args

### ISSUE THREAD

**Issue by swiknaba** [marcqualie/ecsx#3]
Running for instance `ecsx task-definitions`, the AWS CLI will default to use the `default` account found in `.aws/credentials`.

It would be nice if this tool could pass the `--profile XXX` command from the AWS cli through, e.g.

```
ecsx task-definitions --profile=my-second-aws-account
```

potentially, pass-through args could just be prefixed, e.g. `ecsx task-definitions --aws-profile=my-second-aws-account` would then pass `--profile=xx` through to the AWS cli.

**Comment by marcqualie** [comment]
Could possibly add this as a global flag.

It's currently possible to configure the environment via env vars as well (the AWS SDK used under the hood already supports this):

```shell
export AWS_PROFILE=my-second-aws-account
```

This can also be used to set a whole number of other aws specific things, without needing to modify the cli.

Would this work for your use case @swiknaba, or do you think `--profile` would be needed as well?
